site_name: byteyu

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate  # Dark mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default  # Light mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      pygments_style: material
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: Table of Contents

nav:
  - Home: index.md
  - Notes:
      - Machine Learning:
          - Introduction: Intro-Machine-Learning/01. Introduction.md
      - Numerical PDEs:
          - Introduction: NumericalPDE/index.md
      - High-Performance Computing:
          - Introduction: HPC/index.md


extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - stylesheets/code.css
  - stylesheets/math.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/math.js

extra:
  generator: false  # Remove "Made with MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
